### ISSUE TITLE
Lab Repository Could Not Be Found

### ISSUE THREAD

**Issue by jaeku** [learn-co-curriculum/rails-form_for-on-edit-readme#5]
The Nitrous Button Link is broken. Apparently it cannot find this particular lab upon redirect into the Nitrous console.

**Comment by AnnJohn** [comment]
Hi @jaeku sorry about this. Since this is a technical issue, could you file a bug report? If you hover over your profile pic in Learn, then you'll see a menu with an option to report a bug. In general for Nitrous issues, filing a bug report instead of raising an issue is  the best thing to do. Thanks!
